[project]
name = "deep-rec-sys-amazon-reviews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gensim>=4.3.3",
    "matplotlib>=3.10.0",
    "numpy<2.0.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "surprise>=0.1",
    "torch>=2.6.0",
    "torchinfo>=1.8.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "wandb>=0.19.6",
]
