# m stands for model - i.e model parameters
m:
  num_users: 1335228
  num_products: 71254
  num_conv_filters: 80
  kernel_size: 1
  word_embed_dim: 300
  id_embed_dim: 30
  attention_vector_dim: 20
  feature_vector_dim: 10

# t stands for training - i.e training parameters
t:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 3
  random_seed: 42
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  eval_iters: 500
  eval_batches: 50
  checkpoint_iters: 500
  max_iters: 100